armink/FlashDB

inc/fdb_def.h
inc/flashdb.h
src/fdb_kvdb.c

1. A fix in fdb_kv_to_blob() ? pls check if kv->addr.start should assigned to blob->saved.meta_addr.
2.Add struct fdb_kv_iterator/fdb_kv_iterator_init()/fdb_kv_iterate() , implements public iterator for kvdb.
use it like this:
fdb_kvdb kvdb;
void test_kv_iterator(void)
{
struct fdb_kv_iterator kv_itr;
fdb_kv_iterator_init(&kv_itr);
while(fdb_kv_iterate(&kvdb, &kv_itr)) {
/* Do something with kv_itr.curr_kv */
}
/* Already fetched all kvs */
}

Add public KVDB iterator

---

src/fdb_kvdb.c

fdb_kv_iterate() now returns kv object which status is FDB_KV_WRITE only, as most users have no interest in deprecated KVs

Fix: kv iterator now returns valid kv obj only.

---

port/fal/inc/fal_def.h

在rtt4.1.0中，rt_kprintf增加了返回值功能，以符合ISO C标准。 因此不建议使用extern的方式，直接#include <rtthread.h>即可。此外从4.0.3版本往后，RTT增加了__RTTHREAD__全局宏来进行OS判断（目的是为了在其他上游软件包中，可以与nuttx zephyr linux区分开），因此新版本的软件包可以采用__RTTHREAD__宏来直接判断

update for RT-Thread v4.1.0

---

src/fdb_kvdb.c

Please review the change and fix other similar issues if there is any.
This issue caused unaligned writing of grain-64 data to Flash.

fix: use aligned macro to replace unaligned sizeof structure.

---

inc/fdb_low_lvl.h
src/fdb_kvdb.c
src/fdb_utils.c

原先默认认为flash擦除后为0xff，添加了对应的宏定义进行区分，默认`FDB_BYTE_ERASED`定义为0xff，`FDB_BYTE_WRITTEN`定义为0x00，在tc397同类型的flash上运行flashdb需要更换`FDB_BYTE_ERASED`和`FDB_BYTE_WRITTEN`的定义。  
TC397上目前已能够正常运行

支持tc397擦除后为0的flash

---

src/fdb_kvdb.c

修复场景：
当cache满的情况下，更新一个新的key值 A 到cache后，因为初始化的active为0，导致下一个key值 B 再更新到cache里，会把 A给删除。使得满cache的情况下，每次更新key值，都会把上一个key值给从cache中删除。

[kvdb] improve kvdb cache algo when key was first found

---

src/fdb_file.c

Comparing a `size_t` with a `ssize_t` or an `uint32_t` with an `int` gives a warning - fix that by doing an explicit cast.

[fdb] fix comparison of integer expressions of different signedness

---

port/fal/inc/fal_def.h

Platforms that already define an `assert()` function (in `assert.h`) will have a conflict if `assert.h` and `flashdb.h` are included in the same file.
Add an option `FDB_USING_NATIVE_ASSERT` to use the platform's native `assert()` function instead of defining a custom one.

[port/fal] add option to use native assert()

---

inc/fdb_def.h

This is a follow-up to #225
I was wondering why a failed assert would still get me stuck in the endless loop instead of printing the platform's error message. Turns out there is a separate `FDB_ASSERT()` - also make it use the native `assert()` when `FDB_USING_NATIVE_ASSERT` is set.

[fdb] use native assert if FDB_USING_NATIVE_ASSERT is set

---

inc/fdb_low_lvl.h

An error occurred in FDB_ALIGN(size, align) when align is not 2 to the nth power.
The following is the minimal unit test code for the new implementation:
```
#include <stdio.h>
#define FDB_ALIGN(size, align)                      ((size + align -1) - ((size + align -1) % align))
void main(void)
{
printf("FDB_ALIGN(0, 8) : %d\n", FDB_ALIGN(0, 8));
printf("FDB_ALIGN(0, 10) : %d\n", FDB_ALIGN(0, 10));
printf("FDB_ALIGN(10, 10) : %d\n", FDB_ALIGN(10, 10));
printf("FDB_ALIGN(10, 20) : %d\n", FDB_ALIGN(10, 20));
printf("FDB_ALIGN(20, 20) : %d\n", FDB_ALIGN(20, 20));
printf("FDB_ALIGN(20, 10) : %d\n", FDB_ALIGN(20, 10));
printf("FDB_ALIGN(10, 8) : %d\n", FDB_ALIGN(10, 8));
printf("FDB_ALIGN(10, 7) : %d\n", FDB_ALIGN(10, 7));
printf("FDB_ALIGN(7, 10) : %d\n", FDB_ALIGN(7, 10)); …
```

[inc/fdb_low_lvl] fix An error occurred in FDB_ALIGN(size, align)

---

src/fdb_kvdb.c
src/fdb_utils.c

The actual value of `~0UL` is architecture dependent. The `unsigned long` type must be at least 32 bits, but can be larger. Especially on 64-bit systems, `unsigned long` usually is 64 bits long, for which `~0UL` will result in `0xFFFFFFFFFFFFFFFF` instead of `0xFFFFFFFF`. If this is the case, comparisons like `kv->len == ~0UL`, where `kv->len` is of type `uint32_t`, are always false. This commit replaces `~0UL` with the appropriate max value defines from stdint.h.

Replaced `~0UL` in max value checks

---

src/fdb.c

Tiny patch for fixing #222 (FDB_USING_FILE_POSIX_MODE + C optimize cause error)

Relocate `#include<unistd.h>`

---

src/fdb_kvdb.c

`sector->status.store` will be uninitialized when read_section_info fails.
log of Valgrind when read_section_info fails.
```
==175190== Conditional jump or move depends on uninitialised value(s)
==175190==    at 0x8B754F: check_oldest_addr_cb (fdb_kvdb.c:1666)
==175190==    by 0x8B433A: sector_iterator (fdb_kvdb.c:927)
==175190==    by 0x8B865A: fdb_kvdb_init (fdb_kvdb.c:1906)
...
```

interrupt iteraotor when read_section_info fails

---

inc/fdb_cfg.h
src/fdb_kvdb.c
src/fdb_tsdb.c

The new stm32h5xx MCUs only support quad word (128bit) writes to flash. Tested with this driver:
https://github.com/tinic/lightkraken2/blob/main/support/fal_stm32h5xx.c

Support 128bit write granularity for kvdb

---

inc/flashdb.h
src/fdb_tsdb.c

Hi.
In some cases it's necessary to save previously collected TSDB items at a specific timestamp. Real life example: I have a log entries that occurs before application receive valid time from NTP. I'm buffering those log entries in vector together with application uptime when the event occured. Then, when app receive a time from NTP, I'm saving collected log entries into TSDB with adjusted timestamp.

Add ability to append TSDB value at specific timestamp

---

src/fdb_kvdb.c

The initialization is done for the first member only. llvm creates a warning when using `-Wextra`.

[kvdb] Initialize only status explicitly

---

src/fdb_kvdb.c

ASAN reports an error:
```bash
FlashDB/src/fdb_kvdb.c:288:83: runtime error: left shift of 255 by 24 places cannot be represented in type 'int'
```

[fdb_kvdb] fix runtime error

---

src/fdb_kvdb.c

```bash
FlashDB/src/fdb_kvdb.c: In function ‘read_sector_info’:
FlashDB/src/fdb_kvdb.c:488:23: warning: declaration of ‘sector_cache’ shadows a previous local [-Wshadow]
488 |         kv_sec_info_t sector_cache = get_sector_from_cache(db, sector->addr);
|                       ^~~~~~~~~~~~
FlashDB/src/fdb_kvdb.c:421:19: note: shadowed declaration is here
421 |     kv_sec_info_t sector_cache = get_sector_from_cache(db, addr);
|                   ^~~~~~~~~~~~
```

[fdb_kvdb]: fix shadow warning

---

demos/esp32_spi_flash/CMakeLists.txt
samples/tsdb_sample.c
src/fdb.c

@armink can you review these changes?
- size_t should be `zu` as per the discussion here - https://github.com/espressif/esp-idf/issues/11319#issuecomment-1533083268
- there are some uninitialzied errors that I have treated as warnings in cmake
- I have included the switch to 64 bit time stamps - I can remove that if you want.

Fixes to build for IDF w/o errors

---

src/fdb_kvdb.c

Fix linux first run blocking issue (#285) due to db lock.

[fdb_kvdb] fix lock issue to fix block on first run

---

src/fdb_utils.c

If user has set file mode, but file mode is disabled, _fdb_flash_write should return FDB_WRITE_ERR, not FDB_READ_ERR.

[fdb_utils][_fdb_flash_write]: fix returned incorrect error code.

---

src/fdb_kvdb.c

The C library function - strlen() does not accept a null-pointer.

[kvdb] fix null-pointer dereference

---

src/fdb_tsdb.c

https://github.com/armink/FlashDB/pull/302  这个pr确实解决了异常掉电后last time被变为0，但是会导致，上次异常掉电正在写的地址，下次上电后被复写，因为addr没有增加，还是上次FDB_TSL_PRE_WRITE的TSL的地址。

[tsdb][read_sector_info]: fix flash overwrite when abnormal power loss

---

src/fdb_file.c

When `FDB_USING_FILE_LIBC_MODE` is enabled, the `libc` functions `fwrite` and `fread` awaited an incorrect return.
Current function calls want to write `size` bytes once, and wait for the size of bytes written to be returned, but the functions return how many times the `size` was written (written as `1` in the code), which always returns `1`, if it succeeds.
```
On success, fread() and fwrite() return the number of items read
or written.  This number equals the number of bytes transferred
only when size is 1.  If an error occurs, or the end of the file
is reached, the return value is a short item count (or zero).
```
[[source](https://www.man7.org/linux/man-pages/man3/fread.3.html#RETURN_VALUE)]

Fixed a bug with reversed arguments to the `fwrite` and `fread` functions for `libc` file mode.
